### ISSUE TITLE
Play-In-Editor?

### ISSUE THREAD

**Issue by jfaz1** [EvergineTeam/Feedback#103]
Hello,

Giving this engine a test run, can't seem to find the play-in-editor/test button anywhere. I've been just building and running every time. Couldn't find anything in the docs. Is this a feature?

**Comment by Jorgemagic** [comment]
Hi jFaz,

You can click on F5 or go to File menu -> Build & Run option. There is no simulation inside the editor.

![image](https://user-images.githubusercontent.com/694951/143405007-56ee20f2-852d-449a-b0f2-cd537cc8e0ee.png)

 Regards,
Jorge

**Comment by jfaz1** [comment]
Good to know, thanks. I'd see about implementing this feature as it's a very common option in most other engines.
