### ISSUE TITLE
Urgently needs a game sample / better documentation

### ISSUE THREAD

**Issue by jfaz1** [EvergineTeam/Feedback#104]
Hello,

Trying to use this engine for a quick game prototype but the documentation and samples are severely lacking. I remember trying WaveEngine a while back and had the same issue. While the docs are slightly better, they're still very much missing important information. Just a simple third person platformer will do; things like animation states, audio cues, input, etc. 

For instance, it took me 20 minutes just to find out how to move the parent's entity, and even then I don't know if the way I'm doing it is the correct way or not. This is what I'm currently doing inside my behavior:
`this.Owner.FindComponent<Transform3D>().Position = Vector3.Zero;`
Do I really need to call `FindComponent` in order to get an Entity's transform? In that case, doesn't it mean that the more components an Entity has, the more expensive every retrieval of an Entity's transform will be? If this isn't the right way to do it, what is?

**Comment by geomorillo** [comment]
How can we make anything if we cant find how to do it please make some better tutorials

**Comment by Jorgemagic** [comment]
Hi Jfaz1,

I recommend you use the **Bind Components attributes**, you can find the documentation [here](https://docs.evergine.com/manual/basics/bindings/bind_components.html).

```
[BindComponent]
private Transform myTransform;
...
myTransform.Position = Vector3.Zero;
```

We going to continue improving our documentation.

Regards,
Jorge

**Comment by jfaz1** [comment]
> Hi Jfaz1,
> 
> I recommend you use the **Bind Components attributes**, you can find the documentation [here](https://docs.evergine.com/manual/basics/bindings/bind_components.html).
> 
> ```
> [BindComponent]
> private Transform myTransform;
> ...
> myTransform.Position = Vector3.Zero;
> ```
> 
> We going to continue improving our documentation.
> 
> Regards, Jorge

Thanks, that makes more sense!
