### ISSUE TITLE
Drag and Drop assets into properties

### ISSUE THREAD

**Issue by jfaz1** [EvergineTeam/Feedback#105]
Just a general UX improvement which shouldn't be too difficult. I'd add this myself but, not open source 😆 

https://user-images.githubusercontent.com/25165780/143320300-c4e6d5c6-a86b-45d2-95ab-71500d87cf02.mp4

**Comment by Jorgemagic** [comment]
Thanks for your feedback Jfaz1, I added this feature to our roadmap. 

Regards,
Jorge
