### ISSUE TITLE
Web (Web GL 2.0) Initial Project does not build (2021.11.17.2-preview)

### ISSUE THREAD

**Issue by adamthole** [EvergineTeam/Feedback#110]
When creating a new Evergine project that includes "Web (WebGL2.0)" using the 2021.11.17.2-preview release, opening up the associated Web.sln in Visual Studio 2022 I get the following error when trying to build:

Error	MSB4057	The target "WasmBuildApp" does not exist in the project.	MyEvergineProject.Web	C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets	114	

I have the same issue when trying to run the Digital Twin sample.

What am I missing to get these working?

Thanks!

**Comment by sescalada** [comment]
Hi @adamthole, have you installed wasm-tools? Just run following command in a terminal.

dotnet workload install wasm-tools --skip-manifest-update

**Comment by adamthole** [comment]
Hi @sescalada, thank you for your response!

I installed the wasm-tools using your command and after a reboot I am now able to get further along in the build process.  It is now failing with the following error:

Error	MSB4113	Specified condition "$(ExportEvergineAssets)" evaluates to "" instead of a boolean.	EvergineWebTest.Web	C:\Users\adamt\.nuget\packages\evergine.targets.web\2021.11.17.2-preview\build\Evergine.Targets.Web.targets	25	

Here is the relevant line from that file:

<EvergineContentFiles Include="$(EvergineAssetIntermediate)\**\*" Condition="$(ExportEvergineAssets)" />

Any idea how to fix this issue?

Thanks again!

**Comment by sescalada** [comment]
There is a target that should set a value for that variable, but it seems not to be working. Could you please share some diagnostics MSBuild logs?

You can try adding this value manually editing EvergineWebTest.Web.csproj file but I'm not very sure this is going to work:

```  
  <PropertyGroup>
    <DefineConstants>WASM</DefineConstants>
    <GenerateEvergineContent>False</GenerateEvergineContent>
    <GenerateEvergineAssets>True</GenerateEvergineAssets>
    <ExportEvergineAssets>True</ExportEvergineAssets> <!-- this -->
  </PropertyGroup>
```

**Comment by adamthole** [comment]
Thank you for your response!

When I went to do the build with diagnostic logs I used the terminal inside Visual Studio to call msbuild directly, instead of using the built in Visual Studio option to "Build Solution".  When calling msbuild directly, the build works without issue.  Once built using msbuild I can even run it and debug it inside Visual Studio.  If I then clean it and try to build it from Visual Studio it goes back to the same original error.

So it looks like whatever command Visual Studio is calling when I try to build the solution is different than what I am calling:

> msbuild EvergineWebTest.Web.sln -v:diag

Note this command works with or without the diagnostic verbosity set.  

Building the solution manually seems to work without issues for me.  If you want me to try anything else on my end to figure out why the solution isn't building in Visual Studio let me know.  I'm happy to help do what I can to make sure this isn't an issue for others.

I also tried your extra addition to the PropertyGroup, and it fixed the one error, but brought up more errors.  I can provide that log if you are interested.  Given it builds correctly using msbuild directly I didn't think this was worth investigating further, but I could be wrong.

Thanks again!

**Comment by sescalada** [comment]
We have added this as a bug to our backlog. It seems that we have different behaviors on MSBuild targets execution order depending on user doing a rebuild or clean&build from Visual Studio.

I'm closing the issue if you don't have more blocks related to this.

Thanks!

**Comment by adamthole** [comment]
That sounds like a good plan to me.  No blocks here, thanks again!
