### ISSUE TITLE
Error al abrir una escena de la demo de Wave Engine MRTK

### ISSUE THREAD

**Issue by gabrielgt** [EvergineTeam/Feedback#12]
Hola,

Al intentar abrir cualquier escena de la demo me da este error:
![image](https://user-images.githubusercontent.com/3408827/77688676-c5129000-6fa0-11ea-9872-441e54639300.png)

Estoy en el commit [a172cd9] del jueves, 26 de marzo de 2020 13:44:25.
La versión de Wave Engine es la 3.0.0.4731.

¡Gracias!

**Comment by minolo** [comment]
Hola @gabrielgt !

Puedes probar si ocurre el mismo error con la misma version de Wave en un proyecto vacío?

Y por acotar el problema, cual es la tarjeta gráfica que estás utilizando?

Gracias, un saludo!

**Comment by gabrielgt** [comment]
Hola @minolo 

En un proyecto vacío me funcionan bien las escenas y puedo añadir modelos y todo va perfecto. El único que me falla hasta ahora es la demo del MRTK.

La tarjeta gráfica es una NVIDIA Quadro M1000M con driver 25.21.14.2553.

Un saludo!

**Comment by minolo** [comment]
Buenas!

Parece que tenemos problemas diversos con las gráficas Quadro. Lo he reportado internamente y te mantendré informado.

Gracias!
