### ISSUE TITLE
Headless support?

### ISSUE THREAD

**Issue by dbruning** [EvergineTeam/Feedback#122]
Is it possible to use Evergine without ever creating a window? I want to be able to create and save some images to disk from a unit test, and it's difficult/hacky to instantiate a window from inside the unit test.
It looks like this might be possible with DirectX11:
https://gamedev.stackexchange.com/questions/51526/directx11-without-window-attached
https://github.com/carasuca/MinimalOffscreenD3D
... but I don't know enough DirectX to do that myself & wondering if there's an easy way to achieve it with Evergine. Could be a nice additional project for the LowLevelAPI repo?

**Comment by emepetres** [comment]
Hi @dbruning , It is possible but we don't currently support it on Evergine out of the box. We are currently working on some changes for machine learning that include this feature, but it is not ready yet.

We will probably include it on the next major release of Evergine on September, I'll let you know when this is available in the nightly builds. Thank you for your report :)

**Comment by dbruning** [comment]
Thankyou!
