### ISSUE TITLE
Best way to render a point cloud?

### ISSUE THREAD

**Issue by dbruning** [EvergineTeam/Feedback#123]
I need to render a point cloud with hundreds of thousands of points.
#63 talks about using LineBatch3D or LineMeshRenderer3D to do this with lines, but there doesn't seem to be anything similar for points. Is there anything like PointBatch3D or PointCloudRenderer3D?

**Comment by Jorgemagic** [comment]
Hi dbruning,

We are working on a new **PointCloud Evergine Addon** that will be available soon, and allow you to render huge point clouds and used them in your Evergine project. But if you can not wait or you want to develop your custom solution. I recommend you start with a custom mesh _(MeshComponent component)_ with only a vertex buffer _(without an index buffer)_ where each point cloud corresponds to a vertex with position and color and draws the mesh.

```
// My point cloud with 4 points
 VertexPositionColor[] vertexData = new VertexPositionColor[]
 {
        new VertexPositionColor(new Vector3(-0.5f, 0.5f, 0.0f), Color.Blue),
        new VertexPositionColor(new Vector3(0.5f, 0.5f, 0.0f), Color.Red),
        new VertexPositionColor(new Vector3(0.5f, -0.5f, 0.0f), Color.Green),
        new VertexPositionColor(new Vector3(-0.5f, -0.5f, 0.0f), Color.Yellow),
 };

// Create vertex buffer with VertexPositionColor layout
var vBufferDescription = new BufferDescription((uint)Unsafe.SizeOf<VertexPositionColor>() * (uint)this.vertexData.Length,
                                                                BufferFlags.ShaderResource | BufferFlags.VertexBuffer,
                                                                ResourceUsage.Default);
Buffer vBuffer = graphicsContext.Factory.CreateBuffer(this.vertexData, ref vBufferDescription);
VertexBuffer vertexBuffer = new VertexBuffer(vBuffer, VertexPositionColor.VertexFormat);

// Create custom mesh with PointList as primitive topology
Mesh(new VertexBuffer[] { vertexBuffer }, PrimitiveTopology.PointList);
```

**Comment by dbruning** [comment]
Thankyou, I'll give that a try. I made do with a LineMesh of short line segments in the mean time.

**Comment by dbruning** [comment]
Update: I tried this, but was unable to create a Mesh with PrimitiveTopology.PointList, because I get " Primitive topology PointList not supported." thrown from the Mesh constructor (originating from PrimitiveTopologyExtension.ToIndexCount)
Any other guidance or samples you can give would be greatly appreciated - this point cloud is the key of the use case for Evergine.

**Comment by Jorgemagic** [comment]
Hi dbruning, 

You are right, I apologize I found a bug using PointList topology to create a new mesh. I have added this bug to our bug tracker system and I will update you in this thread when the bug is resolved.

On the other hand, We are going to publish a new PointCloud addon in the next release that you can use in your project. Or if you cannot wait you can use our [Priority support service](https://evergine.com/priority-support/) to resolve quickly any doubt and to have hotfixes for the current Evergine stable version.

I hope to update you soon,
Jorge

**Comment by dbruning** [comment]
No problem Jorge. I ended up switching to Monogame for this project; all the best with Evergine and I will check back when Evergine is a little more mature for future projects!
