### ISSUE TITLE
Error en Web al calcular rayo entre la cámara 3D y la posición del ratón

### ISSUE THREAD

**Issue by gabrielgt** [EvergineTeam/Feedback#13]
Hola,

Al calcular en Web un rayo entre la cámara 3D activa y la posición del ratón parece que el rayo se desvía hacia la derecha a medida que nos alejamos del borde izquierdo de la pantalla. En Windows no ocurre.

Aquí se puede ver lo que ocurre en Web:

![WaveEngineBetiJaiRayWeb](https://user-images.githubusercontent.com/3408827/79618553-a4a2a500-810a-11ea-9944-4a6baf22b5e8.gif)

Y lo que ocurre en Windows:

![WaveEngineBetiJaiRayWindows](https://user-images.githubusercontent.com/3408827/79618512-86d54000-810a-11ea-9ed6-473a7fa88ae4.gif)

El código fuente está en este repo: https://github.com/gabrielgt/WaveEngine.Web.Learning 
El código que calcula el rayo está en el fichero [HotspotBehavior.cs](https://github.com/gabrielgt/WaveEngine.Web.Learning/blob/master/BetiJaiDemo/Behaviors/HotspotBehavior.cs)

Un saludo,
   Gabriel

**Comment by MarcosCobena** [comment]
Hola Gabriel, buenos días:

He dado de alta el bug en nuestro sistema, te avisaremos de nuevo cuando podamos ponernos con él.

Gracias,

—Marcos
