### ISSUE TITLE
WebGL2: Error while translating the effect SDFText.wefx

### ISSUE THREAD

**Issue by vicfergar** [EvergineTeam/Feedback#133]
I've found an issue while building a WebGL2 project with the default settings.

## Steps to reproduce
1. Create a new project choosing `WebGL2.0` as an initial platform
2. Open the project folder
3. Open `WebGLTest.Web` solution
4. Build the solution

## Expected result
The solution build without problems

## Actual result
An error is shown while translating the effect SDFText.wefx

### Evergine version: `2022.5.21.1`

![image](https://user-images.githubusercontent.com/6979979/169695762-af49d972-b275-45b5-8595-728c613fef30.png)

**Comment by vicfergar** [comment]
I found a workaround:

1. Open the project within Evergine Studio
2. Open the `SDFText` effect
3. Press the `Profiles` button
4. Clear the `MandatoryCombinations` field. (It shows `All` by default)
5. Press `Save` button to create a copy of the asset in your content

After these steps, you should be able to build the WebGL2 solution without errors.

**Comment by emepetres** [comment]
Thank you @vicfergar , currently we are having some issues in the nightlies with the MandatoryCombinations. We'll look into it!

**Comment by emepetres** [comment]
@vicfergar this issue has been solved on latest nightly
