### ISSUE TITLE
Error añadiendo entidades en ejecución

### ISSUE THREAD

**Issue by gabrielgt** [EvergineTeam/Feedback#14]
Hola,

Al añadir varias entidades (cilindros) al EntityManager durante el ciclo de Update de un componente de comportamiento, se descomponen algunas de las entidades ya existentes.

¿A que no sabéis cuantas entidades hay que añadir para que se rompa? ... ¡22, 22, 22!
Es como un chiste del Dúo Sacapuntas 🤣

Aquí se puede ver lo que pasa:

![WaveEngineBetiJai22Rays](https://user-images.githubusercontent.com/3408827/79621129-8fca0f80-8112-11ea-9f66-b51a4c897e7c.gif)

El código fuente está en este repo: https://github.com/gabrielgt/WaveEngine.Web.Learning
El código que añade las entidades está en el fichero [HotspotBehavior.cs](https://github.com/gabrielgt/WaveEngine.Web.Learning/blob/master/BetiJaiDemo/Behaviors/HotspotBehavior.cs#L68)

Un saludo,
   Gabriel

**Comment by MarcosCobena** [comment]
Hola de nuevo :-)

He registrado el bug internamente; gracias por el detalle al reportarlo, te lo has currado :-)

—Marcos
