### ISSUE TITLE
Creating project fails in Editor, but works in Visual Studio

### ISSUE THREAD

**Issue by CAMongrel** [EvergineTeam/Feedback#153]
**Engine used:** 2022.9.28.6

**Issue:**
When I'm creating a blank new project with only the Windows target, the Editor throws errors at startup. The msbuild auto-detection apparantly detects Visual Studio 2019 and shows the error "error MSB4236: The SDK "Microsoft.NET.Sdk" specified could not be found."

**Result:**
The project cannot be opened or used at all.

**Sidenotes:**
- Manually opening the generated .sln file in Visual Studio 2022 and compiling there works fine.
- I installed Evergine yesterday and the sample (AreaLights) I tried worked fine then, but the same sample also stopped working today.

**Comment by CAMongrel** [comment]
Ok, I believe this issue can be closed. There was a Windows Update yesterday in the evening, which seemingly messed up some paths. I reinstalled/repaired Visual Studio 2022 and now Evergine works again.

Sorry for the confusion.

**Comment by Trifido** [comment]
Hi @CAMongrel, thank you for your report, we are glad it could be solved. 
For any problem or doubt here we are.
Regards,
@Trifido
