### ISSUE TITLE
Missing assets.js when starting any web project

### ISSUE THREAD

**Issue by codeus-de** [EvergineTeam/Feedback#154]
I've just started trying Evergine and really do like the your approach your taking!

One problem immediately arises when I try to run a web project. This is true for "file / new / project" as well as for the included demo projects like DigitalTwin.

All index.html files reference an assets.js file. I can't find this file anywhere and the browser can't either (always getting 404 not found). I assume that because this file is missing the web projects can't be started (stuck at loading screen).

Can you please tell me what to do to get a web app (preferrably Blazor WebAssembly) running?

**Comment by davilovick** [comment]
Hello @codeus-de,

We've detected that one Visual Studio specific version break the web compilation. 
Try to update Visual Studio to the latest version

**Comment by Fydar** [comment]
I seem to be experiencing this issue on the latest version of Visual Studio. I also can't seem to get it to work when publishing from the command line. The `assets.js` file never appears in `wwwroot`, whether in the build or the publish.

@codeus-de were you able to solve your issue?

**Comment by Fydar** [comment]
My mistake! I had another build error that I didn't notice as it was during the emscripten build step.

It looks like it might be an issue with Bullet physics. I removed `<PackageReference Include="Evergine.Bullet" Version="2023.3.1.2" />` from my `.csproj` and everything started working.

```txt
EXEC : error : undefined symbol: btCollisionConfiguration_getClosestPointsAlgorithmCreateFunc (referenced by top-level compiled C/C++ code) [C:\Users\USER\Documents\APPLICATION\APPLICATION.Web\APPLICATION.Web.csproj]
EXEC : warning : Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols [C:\Users\USER\Documents\APPLICATION\APPLICATION.Web\APPLICATION.Web.csproj]
EXEC : warning : To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0` [C:\Users\USER\Documents\APPLICATION\APPLICATION.Web\APPLICATION.Web.csproj]
EXEC : warning : _btCollisionConfiguration_getClosestPointsAlgorithmCreateFunc may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library [C:\Users\USER\Documents\APPLICATION\APPLICATION.Web\APPLICATION.Web.csproj]
EXEC : error : undefined symbol: btIDebugDraw_setDefaultColors (referenced by top-level compiled C/C++ code) [C:\Users\USER\Documents\APPLICATION\APPLICATION.Web\APPLICATION.Web.csproj]
EXEC : warning : _btIDebugDraw_setDefaultColors may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library [C:\Users\USER\Documents\APPLICATION\APPLICATION.Web\APPLICATION.Web.csproj]
EXEC : error : Aborting compilation due to previous errors [C:\Users\USER\Documents\APPLICATION\APPLICATION.Web\APPLICATION.Web.csproj]
```

**Comment by Kanawanagasaki** [comment]
Hello, I just installed Evergine and tried to create a web project, however I came across the same problem described above: `assets.js` is never created, browser cannot find it (404). Removing `<PackageReference Include="Evergine.Bullet" Version="2023.9.28.511" />` did not help

**Comment by davilovick** [comment]
Hi @Kanawanagasaki,
I think that you miss to install the `wasm-tools-net6` workload? 
In a command line, execute:
`dotnet workload install wasm-tools-net6`

Here you can find more information: https://docs.evergine.com/2023.9.28/manual/platforms/web/index.html

Some times ago, you only need to install the `wasm-tools` workload, but since recently NET7 broke the backward compatibility in wasm tools, it split the workload for a NET6 specific.

Best regards

**Comment by Kanawanagasaki** [comment]
Thank you @davilovick !! It helped and web projects now work!
