### ISSUE TITLE
Memory leaks when resizing 3D primitives (namely spheres)

### ISSUE THREAD

**Issue by navrc1** [EvergineTeam/Feedback#157]
Hello,

I am writing to express my admiration for your framework and its capabilities. I have been exploring its potential for a scientific application; however, I have encountered an issue related to memory leaks when resizing primitives, specifically spheres.

To demonstrate the problem, I have made modifications to your Sample WPF application and created a simulation of the memory leak scenario. You can access the modified code and sample application at this GitHub repository: https://github.com/navrc1/EvergineMemoryLeakExample . When you run the application in Visual Studio, you will notice a significant increase in memory usage when the sphere resizing feature is toggled using the provided button.

I kindly request your assistance in resolving this memory leak issue. Any efforts to address this matter would be greatly appreciated.

Thank you for your attention to this matter.

Best regards,
Jan Navrátil

**Comment by Trifido** [comment]
Hi @navrc1 , first of all I apologize for the delay in responding. We have had a lot of work these months.
The problem in this case is that with the "Size" parameter the whole 3D mesh is modified, this information remains cached and in the long run it increases the memory usage.
My recommendation is that for all type of transformations that are not going to affect the structure of the geometry, use the Transform3D component. With this component you will be able to do transformations like scaling. Here is an example.

`
[BindComponent]
 protected Transform3D transform;

  protected override void Update(TimeSpan gameTime) {
      TotalTime += gameTime;
      var size = (float)Math.Sin(TotalTime.TotalSeconds) + 1.1f;
      this.transform.Scale = new Vector3(size);
  }
`
I hope this can help you.
Regards.

**Comment by navrc1** [comment]
Hello @Trifido,

Thank you very much, it helped a lot! The suggested solution makes sense, I unfortunately initially missed the information in the official documentation.

With best wishes
Jan Navrátil
