### ISSUE TITLE
Add model

### ISSUE THREAD

**Issue by JuandreG** [EvergineTeam/Feedback#159]
Hello.

Is it possible to add/load model files like .glb at runtime? What I mean is after we have created a UWP or WPF application from Evergine Studio, in the resulting application when it runs is it possible for me to click a button that would bring up a file picker, I then select the file and have the model show up in the window? a Model viewer of sorts.

In the API reference I see a `Evergine.Assets.Importers.GltfModel` namespace with a `GltfImporterContext`, is this the way to go?

**Comment by Trifido** [comment]
Hello @JuandreG,
First of all, I am sorry for the delay in responding. We have had a lot of work during these summer months.
Evergine, currently uses its own formats.
While it can certainly be done, it is a complex process.
To do this you would need to create your own importer and then create a model with some of the different fields that I put below.

```
// Use the AssetDirectory and pass the path of the 3d model
var asset = this.assetsDirectory.Open("MyContent/my3DModel.glb");
// Use your custom importer
var myImporter = new MyImporter();
var myObject = myImporter.Import(asset);
//Create a Evergine Model and Initialize it with meshes, materiales, texture, animation, etc... (depends on the 3d model)
Model model = new Model();
// Add meshes to the mesh container
model.MeshContainers = new MeshContainer[] { ConvertObjectInMesh(myObject) };
model.RootNodes = new int[] { 0 };
```

More info about Model class: [https://docs.evergine.com/2023.3.1/api/Evergine.Framework.Graphics.Model.html](url)
Regards,
@Trifido

**Comment by JuandreG** [comment]
Okay thank you
