### ISSUE TITLE
Animar modelos en Wave Engine 3

### ISSUE THREAD

**Issue by gabrielgt** [EvergineTeam/Feedback#16]
Hola,

Estoy intentando animar el modelo https://github.com/WaveEngine/Samples/blob/master/Graphics3D/IsisTemple/Content/Assets/Models/isis.fbx con Wave Engine 3 pero no lo consigo.

Lo he cargado desde el editor y luego estoy haciendo esto:

```
var isis = Managers.EntityManager.Find("isis_fbx");
var animation3DComponent = isis.FindComponent<Animation3D>();
animation3DComponent.PlayAnimation("Take 001");
```

Y me da una excepción de "Object reference not set to an instance of an object" aquí:
```
   at WaveEngine.Components.Animation.AnimationTrackClip.InitializeClip()
   at WaveEngine.Components.Animation.AnimationBlendClip.BaseInitializeClip(NodeHierarchyMapping hierarchyMapping)
```

Por cierto, la versión que estoy utilizando es la 3.0.0.4932-preview3.
¿Alguna idea?
¡Gracias!

Saludos,
   Gabriel

**Comment by ma3se** [comment]
Hola Gabriel.
Por ahora skinning y morphong no está soportado en Wave Engine 3. Por suerte estamos ultimandolo para incluirlo en una próxima versión. 

Un saludo.
Antonio.

**Comment by gabrielgt** [comment]
Genial Antonio,

Avísame cuando esté listo y vuelvo a probar.

Gracias!
