### ISSUE TITLE
Value conversion

### ISSUE THREAD

**Issue by JuandreG** [EvergineTeam/Feedback#161]
Hello.

In evergine studio whenever I try to type in a value in the Entity Details pane I see the error "Value '2.000' could not be converted", when you use the up/down keys to adjust the value it works fine but not when typing a value. When the error comes up it does not seem to assign it either, the only way to get rid of it is to use the up/down keys but the typed value then reverts back to it's initial value.

![image](https://github.com/EvergineTeam/Feedback/assets/54146697/264d74c7-8eac-4a1f-a5b5-9510e95ebe61)

I am on version 2023.3.1.1 of Evergine Studio

**Comment by Trifido** [comment]
Hi @JuandreG,
Thank you very much for your report. I have tried to replicate the bug without success in that version. Have you tried with the latest release? Try instead of putting "2.000" use the comma and put "2,000".
Regards,
@Trifido

**Comment by Trifido** [comment]
These are my preferences:
![image](https://github.com/EvergineTeam/Feedback/assets/6890573/b810bbcd-2e39-438c-9f17-40de4d047bbe)

It's strange, we'll check it out.
Could you check if the same thing happens with other 3D primitives, for example modifying the diameter of a sphere mesh?

**Comment by Trifido** [comment]
Hi @JuandreG,

We think we have found the problem.
In the meantime for your solution, what should be done is to modify in the operating system the numerical format. There seems to be a problem with the commas and dots. Check that the decimal symbol is the comma and the digit grouping symbol is the dot. As in the image below.
![format](https://github.com/EvergineTeam/Feedback/assets/6890573/c135010b-780e-446a-b692-24541e6b7f90)
Control Panel -> Region -> Additional settings

Regards,
@Trifido

**Comment by JuandreG** [comment]
Hi @Trifido 

Thank you. That did solve the problem. The error no longer appears and it assets react to value changes.

Regards
