### ISSUE TITLE
React Template Project Build Error

### ISSUE THREAD

**Issue by Scubaboy** [EvergineTeam/Feedback#174]
Hi,

When I try to build a react template project I get the following error:

![image](https://github.com/EvergineTeam/Feedback/assets/6407221/7e59e85e-cfca-4aac-9b4c-bfbb5125bda6)

> Build started...
1>------ Build started: Project: ReactCAD, Configuration: Debug Any CPU ------
1>ReactCAD -> C:\DevRepos\Evergine\ReactCAD\ReactCAD\ReactCAD\bin\Debug\netstandard2.0\ReactCAD.dll
2>------ Build started: Project: ReactCAD.WebReact, Configuration: Debug Any CPU ------
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Samplers\LinearClampSampler.wesp'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\RenderLayers\Alpha.werl'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\RenderLayers\Opaque.werl'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\RenderLayers\Additive.werl'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Samplers\LinearWrapSampler.wesp'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\RenderLayers\Skybox.werl'
2>Asset exported: 'C:\DevRepos\Evergine\ReactCAD\ReactCAD\Content\Scenes\MyScene\Environment\SceneReflectionProbe.werp'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\PostProcessingGraphs\DefaultPostProcessingGraph.wepp'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\RenderQuad.wefx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\SDFText.wefx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\DistortionEffect.wefx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\LineBatchEffect.wefx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\ParticlesEffect.wefx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\BillboardEffect.wefx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\SkyboxEffect.wefx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Materials\DistortionMat.wemt'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Materials\DefaultMaterial.wemt'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\AtmosphericQuadEffect.wefx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\AtmosphericEffect.wefx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Textures\dfgLut.png.wetx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\LineEffect.wefx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\SpriteBatchEffect.wefx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Textures\PostProcessing\FlareGradient.png.wetx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Textures\particle.png.wetx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Textures\PostProcessing\FlareStarburst.png.wetx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Textures\PostProcessing\DistortionTexture.png.wetx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Fonts\Arial.ttf.weft'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Textures\Checker.png.wetx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Textures\PostProcessing\BlueNoise.png.wetx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Textures\PostProcessing\LensDirt00.png.wetx'
2>Asset exported: 'C:\Users\RobCawsey\.evergine\packages\Evergine.Core\2023.9.28.511\Content\Effects\StandardEffect.wefx'
2>ReactCAD.WebReact -> C:\DevRepos\Evergine\ReactCAD\ReactCAD\ReactCAD.WebReact\bin\Debug\net6.0\ReactCAD.WebReact.dll
2>ReactCAD.WebReact (Blazor output) -> C:\DevRepos\Evergine\ReactCAD\ReactCAD\ReactCAD.WebReact\bin\Debug\net6.0\wwwroot
3>------ Build started: Project: reactcad.react.spa, Configuration: Debug Any CPU ------
3>npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
3>npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.19.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
3>npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
3>npm WARN deprecated @babel/plugin-proposal-class-static-block@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-static-block instead.
3>npm WARN deprecated @babel/plugin-proposal-dynamic-import@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.
3>npm WARN deprecated @babel/plugin-proposal-export-namespace-from@7.18.9: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.
3>npm WARN deprecated @babel/plugin-proposal-json-strings@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.
3>npm WARN deprecated @babel/plugin-proposal-logical-assignment-operators@7.18.9: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
3>npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
3>npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
3>npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.19.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
3>npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
3>npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.18.9: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
3>npm WARN deprecated @babel/plugin-proposal-private-methods@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
3>npm WARN deprecated @babel/plugin-proposal-private-property-in-object@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-property-in-object instead.
3>npm WARN deprecated @babel/plugin-proposal-unicode-property-regex@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
3>npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
3>npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
3>npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
3>npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
3>npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
3>
3>> core-js@3.25.5 postinstall C:\DevRepos\Evergine\ReactCAD\ReactCAD\reactcad.react.spa\node_modules\core-js
3>> node -e "try{require('./postinstall')}catch(e){}"
3>
3>[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
3>
3>[96mThe project needs your help! Please consider supporting of core-js:[0m
3>[96m>[94m https://opencollective.com/core-js [0m
3>[96m>[94m https://patreon.com/zloirock [0m
3>[96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
3>
3>[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
3>
3>
3>> core-js-pure@3.25.5 postinstall C:\DevRepos\Evergine\ReactCAD\ReactCAD\reactcad.react.spa\node_modules\core-js-pure
3>> node -e "try{require('./postinstall')}catch(e){}"
3>
3>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^2.3.2 (node_modules\react-scripts\node_modules\fsevents):
3>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
3>
3>added 1256 packages from 683 contributors and audited 1262 packages in 87.983s
3>
3>212 packages are looking for funding
3>  run `npm fund` for details
3>
3>found 79 vulnerabilities (42 moderate, 21 high, 16 critical)
3>  run `npm audit fix` to fix them, or `npm audit` for details
3>
3>> reactcad.react.spa@0.1.0 compile C:\DevRepos\Evergine\ReactCAD\ReactCAD\reactcad.react.spa
3>> npm run evergine:copy --configuration=%npm_config_configuration%
3>
3>
3>> reactcad.react.spa@0.1.0 evergine:copy C:\DevRepos\Evergine\ReactCAD\ReactCAD\reactcad.react.spa
3>> npm run evergine:copy:wasm --configuration=%npm_config_configuration% && npm run evergine:copy:assets --configuration=%npm_config_configuration% && npm run evergine:copy:content --configuration=%npm_config_configuration% && npm run evergine:copy:evergine --configuration=%npm_config_configuration%
3>
3>
3>> reactcad.react.spa@0.1.0 evergine:copy:wasm C:\DevRepos\Evergine\ReactCAD\ReactCAD\reactcad.react.spa
3>> ncp ../ReactCAD.WebReact/bin/%npm_config_configuration%/net6.0/wwwroot/_framework public/_framework
3>
3>
3>> reactcad.react.spa@0.1.0 evergine:copy:assets C:\DevRepos\Evergine\ReactCAD\ReactCAD\reactcad.react.spa
3>> ncp ../ReactCAD.WebReact/bin/%npm_config_configuration%/net6.0/wwwroot/assets.js public/assets.js
3>
3>There were errors during the copy.
3>EXEC : error : ENOENT: no such file or directory, lstat 'C:\DevRepos\Evergine\ReactCAD\ReactCAD\ReactCAD.WebReact\bin\Debug\net6.0\wwwroot\assets.js'
3>npm ERR! code ELIFECYCLE
3>npm ERR! errno 1
3>npm ERR! reactcad.react.spa@0.1.0 evergine:copy:assets: `ncp ../ReactCAD.WebReact/bin/%npm_config_configuration%/net6.0/wwwroot/assets.js public/assets.js`
3>npm ERR! Exit status 1
3>npm ERR!
3>npm ERR! Failed at the reactcad.react.spa@0.1.0 evergine:copy:assets script.
3>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
3>
3>npm ERR! A complete log of this run can be found in:
3>npm ERR!     C:\Users\RobCawsey\AppData\Roaming\npm-cache\_logs\2023-11-07T09_56_02_748Z-debug.log
3>npm ERR! code ELIFECYCLE
3>npm ERR! errno 1
3>npm ERR! reactcad.react.spa@0.1.0 evergine:copy: `npm run evergine:copy:wasm --configuration=%npm_config_configuration% && npm run evergine:copy:assets --configuration=%npm_config_configuration% && npm run evergine:copy:content --configuration=%npm_config_configuration% && npm run evergine:copy:evergine --configuration=%npm_config_configuration%`
3>npm ERR! Exit status 1
3>npm ERR!
3>npm ERR! Failed at the reactcad.react.spa@0.1.0 evergine:copy script.
3>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
3>
3>npm ERR! A complete log of this run can be found in:
3>npm ERR!     C:\Users\RobCawsey\AppData\Roaming\npm-cache\_logs\2023-11-07T09_56_02_766Z-debug.log
3>npm ERR! code ELIFECYCLE
3>npm ERR! errno 1
3>npm ERR! reactcad.react.spa@0.1.0 compile: `npm run evergine:copy --configuration=%npm_config_configuration%`
3>npm ERR! Exit status 1
3>npm ERR!
3>npm ERR! Failed at the reactcad.react.spa@0.1.0 compile script.
3>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
3>
3>npm ERR! A complete log of this run can be found in:
3>npm ERR!     C:\Users\RobCawsey\AppData\Roaming\npm-cache\_logs\2023-11-07T09_56_02_781Z-debug.log
3>C:\Users\RobCawsey\.nuget\packages\microsoft.visualstudio.javascript.sdk\0.5.45-alpha\Sdk\Sdk.targets(127,9): error MSB3073: The command "npm install && npm run compile --configuration=Debug" exited with code 1.
3>Done building project "reactcad.react.spa.esproj" -- FAILED.
4>------ Build started: Project: ReactCAD.Host, Configuration: Debug Any CPU ------
4>ReactCAD.Host -> C:\DevRepos\Evergine\ReactCAD\ReactCAD\ReactCAD.Host\bin\Debug\net6.0\ReactCAD.Host.dll
========== Build: 3 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 09:54 and took 01:37.070 minutes ==========

I was following this post https://evergine.com/introducing-evergine-react-template/

**Comment by Jorgemagic** [comment]
Hi Scubaboy,

I think the issue you are experiencing is relative to wasm-tools. Sometimes, after updating the .NET SDK, it's necessary to reinstall the wasm-tools again.

I recommend that you perform a reinstallation using the following command:
`dotnet workload install wasm-tools-net6`

I  hope that this solution resolves your problem. Please let me know if you need any further assistance or if the issue persists.

Best,
Jorge

**Comment by Scubaboy** [comment]
@Jorgemagic Fantastic that's fixed the issue. Thanks!
