### ISSUE TITLE
Not run new project in Evergine Studio

### ISSUE THREAD

**Issue by DIMANRUS** [EvergineTeam/Feedback#186]
I created an empty project, but it doesn't start. Everything is built and run from the CLI and VS. Please help me, I like your engine, this problem has been going on for over a year.
![image](https://github.com/EvergineTeam/Feedback/assets/41239551/42f8e4a1-8835-4968-b2ac-ec5d8911dd5b)

**Comment by DIMANRUS** [comment]
![image](https://github.com/EvergineTeam/Feedback/assets/41239551/426740a9-b50e-49ec-baa6-add1212302ab)
![image](https://github.com/EvergineTeam/Feedback/assets/41239551/0a6c5f5f-257e-433e-869d-db36ac6a79a7)

**Comment by CreepyCoderMC** [comment]
Hi DIMANRUS, Hope you are well. I'm new to Evergine so please don't kill me, if I'm not always 100% correct. I have stumbled on that same problem a few times but I discovered that if I open the visual studio project and rebuild the project I can then open the Evergine Project with out any errors. But I will also mention that I'm more experimenting with the MAUI,net combined with Evegine.

**Comment by DIMANRUS** [comment]
> Привет, ДИМАНРУС, надеюсь, у тебя все хорошо. Я новичок в Evergine, поэтому, пожалуйста, не убивайте меня, если я не всегда прав на 100%. Я натыкался на ту же проблему несколько раз, но обнаружил, что если я открою проект Visual Studio и перестрою (иногда мне нужно сначала очистить сборку) проект, я смогу затем открыть проект Evergine без каких-либо ошибок. Но я также упомяну, что я больше экспериментирую с MAUI, net в сочетании с Evegine.

Thanks, but it didn't solve my problem. Interestingly, on the other PC, everything is fine. There are too many loads in Visual Studio on my PC, maybe something is confusing.

**Comment by DIMANRUS** [comment]
Hello. I found out the reason from the log file. He couldn't find powershell. To do this, add this path to the environment variables -> Path C:\Windows\System32\WindowsPowerShell\v1.0 Everything is working now. Some other program changed my environment variables during installation, as many other things sometimes fell off and added manually.
