### ISSUE TITLE
License

### ISSUE THREAD

**Issue by juhanikarlsson** [EvergineTeam/Feedback#30]
Hi wavers,

First off really interesting project! I really like the effort going to support .net core ect. but I can't find the license and explanation is it open source or just free?

I was thinking of using Wave for my pet project as I need light engine on the server side but I'm worried what will happen to my project if you go out of business or something hah!

Also can WPF be used for the UI?

Thanks,
-J

**Comment by jcant0n** [comment]
Hi juhanikarlsson,

Wave is the graphics engine we use at PlainConcepts company to develop projects, It is partialy opensource and free, so you can use this for your pet or commercial projects.

The WaveEngine 3.0 editor is based on WPF so the integration is really good, there is a WPF WindowsSystem in this nuget package that you can use: https://www.nuget.org/packages/WaveEngine.WPF

Hope this helps!

**Comment by Thaina** [comment]
@jcant0n Is the waveengine itself opensourced or will be opensourced in the future?

**Comment by jcant0n** [comment]
Hello Thaina,

The WaveEngine project is in a visualstudio online repository now, we want to move the project to github before that.

But as you can see all the new extensions and bindings are open-source and we use these from nugets packages, so we are moving in that direction:
https://github.com/WaveEngine/Vulkan.NET
https://github.com/WaveEngine/RenderDoc.NET
https://github.com/WaveEngine/MixedRealityToolkit-WaveEngine
https://github.com/WaveEngine/AzureRemoteRendering
https://github.com/WaveEngine/OpenGL.NET
https://github.com/WaveEngine/WebGPU.NET

**Comment by aaronfranke** [comment]
> The WaveEngine 3.0 editor is based on WPF so the integration is really good

Are there any plans to have the editor on Mac or Linux? WPF sounds like a huge hinderance to this.

Have the WaveEngine team considered writing the editor UI with the same tools that are used to make games in WaveEngine, such as `WaveEngine.Framework.UI` and `WaveEngine.Components.UI`? This is what Godot does, and it has resulted in one of the best UI systems I've ever used, while making the editor easily portable to any platform it can export to.

**Comment by emepetres** [comment]
Hi @aaronfranke thank you for your feedback and sorry for the late response. For the moment we are not considering using a different UI than WPF, but it is definitely something that will address in the next versions of Evergine Studio.

I'm closing this as the subject is different from the original issue, please feel free to create a new one if you feel so.
