### ISSUE TITLE
Is there any way to embed the game engine to xamarin.forms？

### ISSUE THREAD

**Issue by hefujie1988** [EvergineTeam/Feedback#31]
Generated Android project looks a lot like Xamarin. Android, is there any way to convert to xamarin.Forms project, to make xamarin.Forms project display 3D models, just like Urhosharp

**Comment by monheritage** [comment]
In case you won't find the solution here, I can recommend [url=https://rocketech.it/?utm_source=google&utm_medium=forum&utm_campaign=december]https://rocketech.it[/url] to ask for help.

**Comment by emepetres** [comment]
@hefujie1988 thank you for your report and sorry for the late response, we'll check whenever possible. If you need a quick resolution, please contact our [priority support](https://evergine.com/priority-support/).

**Comment by sescalada** [comment]
We don't have support for that, so you have to implement it by your own. A custom renderer would be necessary, as stated here https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/view. Taking parts from the code of MainActivity from current template to that renderer.
