### ISSUE TITLE
Volumetric rendering

### ISSUE THREAD

**Issue by ZenoArrow** [EvergineTeam/Feedback#43]
Does WaveEngine support volumetric rendering? If not, are there plans to support it in the future? This would be a prerequisite for any engine the company I work for chooses to work with. Thanks in advance.

**Comment by jcant0n** [comment]
Hello ZeroArrow,

We have used WaveEngine to create volumetric rendering for some healthcare industry projects, using GPU directly to make rendering possible on devices like HoloLens.

Here some videos:
https://www.youtube.com/watch?v=eyF-TE-pIBA
https://www.youtube.com/watch?v=BjIxcjoK13o
