### ISSUE TITLE
Bug in empty project

### ISSUE THREAD

**Issue by FrankBusch68** [EvergineTeam/Feedback#52]
Hi, 
I'm just new, so please forgive a duplicate issue if so.

I just startet WaveEngine 3.1 Preview 2 and created a new project for all platforms.
Then I save this without editing, just the blank stuff.

Next step was opening windows solution in VS2019 and start it. Worked fine (which means it showd just an empty window because nothing was defined)
Then I opened the Android solution and tried to start it (an emulator is attached).
I got a couple of error messages.
I will post them after my text.
If I make a mistake or you need more info to find the bugs, just send me a massage.
Thanks in advance
Frank

An now the error-reporting list

Exception: Translation error: hlsl.hlsl:31:31: error: use of undeclared identifier 'blend'
        Output[threadID.xy] = float4(blend, 1.0);
                                     ^

   bei WaveEngine.HLSLEverywhere.HLSLTranslator.HLSLToBinarySPIRV(String hlslSource, ShaderStages stage, GraphicsProfile profile, String entryPoint) in C:\agent\_work\3\s\src\Tools\WaveEngine.HLSLEverywhere\HLSLTranslator.cs:Zeile 246.
   bei WaveEngine.Assets.Exporters.EffectExporter.TranslateShaderToBackend(GraphicsBackend graphicsBackend, PreprocessShader cleanedSource, ShaderStages stage, String entryPoint, CompilerParameters parameters) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 296.
   bei WaveEngine.Assets.Exporters.EffectExporter.Precompile(GraphicsBackend graphicsBackend, PreprocessShader cleanedSource, PassSection pass, String[] directives, PrecompiledCombination compiledCombination, List`1 files) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 211.
   bei WaveEngine.Assets.Exporters.EffectExporter.PrecompileCombination(GraphicsBackend graphicsBackend, List`1 files, ShaderAnalyzer analyzer, PassSection pass, PrecompiledPass precompiledPass, String[] directives) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 205.
   bei WaveEngine.Assets.Exporters.EffectExporter.ExportCompiledShaders(Guid id, String shaderSource, ProjectProfile projectProfile, EffectProfile profile, GraphicsBackend graphicsBackend, DirectivesGroup[]& directivesGroups, List`1& precompiledPasses, GraphicsResourceInfo[]& precompiledResourceLayoutInfo, List`1 files, String projectContent) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 184.
   bei WaveEngine.Assets.Exporters.EffectExporter.<GenerateAssetParts>d__4.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 56.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WaveEngine.Assets.Exporters.AssetExporter`2.<ExportOutputFile>d__1.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\AssetExporter`2.cs:Zeile 36.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WaveEngine.Assets.Exporters.BaseAssetExporter`2.<BaseExport>d__3.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\BaseAssetExporter`2.cs:Zeile 65.	Fisch.Android	C:\Users\fbusc\Documents\Fisch\Content\Computes\Blend.wefx		

Exception: Translation error: hlsl.hlsl:64:29: error: use of undeclared identifier 'BladesNumber'
        PolarCoord.x *= ( cos(PI / BladesNumber) / ( cos(PolarCoord.y - (2.0 * PI / BladesNumber) * floor((BladesNumber * PolarCoord.y + PI) / 2.0 / PI ) )));
                                   ^
hlsl.hlsl:64:78: error: use of undeclared identifier 'BladesNumber'
        PolarCoord.x *= ( cos(PI / BladesNumber) / ( cos(PolarCoord.y - (2.0 * PI / BladesNumber) * floor((BladesNumber * PolarCoord.y + PI) / 2.0 / PI ) )));
                                                                                    ^
hlsl.hlsl:64:101: error: use of undeclared identifier 'BladesNumber'
        PolarCoord.x *= ( cos(PI / BladesNumber) / ( cos(PolarCoord.y - (2.0 * PI / BladesNumber) * floor((BladesNumber * PolarCoord.y + PI) / 2.0 / PI ) )));
                                                                                                           ^

   bei WaveEngine.HLSLEverywhere.HLSLTranslator.HLSLToBinarySPIRV(String hlslSource, ShaderStages stage, GraphicsProfile profile, String entryPoint) in C:\agent\_work\3\s\src\Tools\WaveEngine.HLSLEverywhere\HLSLTranslator.cs:Zeile 246.
   bei WaveEngine.Assets.Exporters.EffectExporter.TranslateShaderToBackend(GraphicsBackend graphicsBackend, PreprocessShader cleanedSource, ShaderStages stage, String entryPoint, CompilerParameters parameters) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 296.
   bei WaveEngine.Assets.Exporters.EffectExporter.Precompile(GraphicsBackend graphicsBackend, PreprocessShader cleanedSource, PassSection pass, String[] directives, PrecompiledCombination compiledCombination, List`1 files) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 211.
   bei WaveEngine.Assets.Exporters.EffectExporter.PrecompileCombination(GraphicsBackend graphicsBackend, List`1 files, ShaderAnalyzer analyzer, PassSection pass, PrecompiledPass precompiledPass, String[] directives) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 205.
   bei WaveEngine.Assets.Exporters.EffectExporter.ExportCompiledShaders(Guid id, String shaderSource, ProjectProfile projectProfile, EffectProfile profile, GraphicsBackend graphicsBackend, DirectivesGroup[]& directivesGroups, List`1& precompiledPasses, GraphicsResourceInfo[]& precompiledResourceLayoutInfo, List`1 files, String projectContent) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 184.
   bei WaveEngine.Assets.Exporters.EffectExporter.<GenerateAssetParts>d__4.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 56.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WaveEngine.Assets.Exporters.AssetExporter`2.<ExportOutputFile>d__1.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\AssetExporter`2.cs:Zeile 36.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WaveEngine.Assets.Exporters.BaseAssetExporter`2.<BaseExport>d__3.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\BaseAssetExporter`2.cs:Zeile 65.	Fisch.Android	C:\Users\fbusc\Documents\Fisch\Content\Computes\BokehBlur.wefx		

Exception: Translation error: hlsl.hlsl:57:39: error: use of undeclared identifier 'qualityEdgeThreshold'
    float rangeMaxScaled = rangeMax * qualityEdgeThreshold;
                                      ^
hlsl.hlsl:59:33: error: use of undeclared identifier 'qualityEdgeThresholdMin'
    float rangeMaxClamped = max(qualityEdgeThresholdMin, rangeMaxScaled);
                                ^
hlsl.hlsl:417:31: error: use of undeclared identifier 'qualitySubPix'
    float subpixH = subpixG * qualitySubPix;
                              ^

   bei WaveEngine.HLSLEverywhere.HLSLTranslator.HLSLToBinarySPIRV(String hlslSource, ShaderStages stage, GraphicsProfile profile, String entryPoint) in C:\agent\_work\3\s\src\Tools\WaveEngine.HLSLEverywhere\HLSLTranslator.cs:Zeile 246.
   bei WaveEngine.Assets.Exporters.EffectExporter.TranslateShaderToBackend(GraphicsBackend graphicsBackend, PreprocessShader cleanedSource, ShaderStages stage, String entryPoint, CompilerParameters parameters) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 296.
   bei WaveEngine.Assets.Exporters.EffectExporter.Precompile(GraphicsBackend graphicsBackend, PreprocessShader cleanedSource, PassSection pass, String[] directives, PrecompiledCombination compiledCombination, List`1 files) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 211.
   bei WaveEngine.Assets.Exporters.EffectExporter.PrecompileCombination(GraphicsBackend graphicsBackend, List`1 files, ShaderAnalyzer analyzer, PassSection pass, PrecompiledPass precompiledPass, String[] directives) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 205.
   bei WaveEngine.Assets.Exporters.EffectExporter.ExportCompiledShaders(Guid id, String shaderSource, ProjectProfile projectProfile, EffectProfile profile, GraphicsBackend graphicsBackend, DirectivesGroup[]& directivesGroups, List`1& precompiledPasses, GraphicsResourceInfo[]& precompiledResourceLayoutInfo, List`1 files, String projectContent) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 184.
   bei WaveEngine.Assets.Exporters.EffectExporter.<GenerateAssetParts>d__4.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 56.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WaveEngine.Assets.Exporters.AssetExporter`2.<ExportOutputFile>d__1.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\AssetExporter`2.cs:Zeile 36.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WaveEngine.Assets.Exporters.BaseAssetExporter`2.<BaseExport>d__3.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\BaseAssetExporter`2.cs:Zeile 65.	Fisch.Android	C:\Users\fbusc\Documents\Fisch\Content\Computes\FXAA.wefx		

Exception: Translation error: hlsl.hlsl:23:21: error: use of undeclared identifier 'GAUSS_KERNEL'
        for(int i = 0; i < GAUSS_KERNEL; i++)
                           ^
hlsl.hlsl:25:31: error: use of undeclared identifier 'gaussianOffsets'
                float2 offset = direction * gaussianOffsets[i];
                                            ^
hlsl.hlsl:27:10: warning: implicit truncation of vector type
                float3 pixel = input[uv];
                       ^
hlsl.hlsl:28:20: error: use of undeclared identifier 'gaussianWeightsNormalized'
                color += pixel * gaussianWeightsNormalized[i];
                                 ^

   bei WaveEngine.HLSLEverywhere.HLSLTranslator.HLSLToBinarySPIRV(String hlslSource, ShaderStages stage, GraphicsProfile profile, String entryPoint) in C:\agent\_work\3\s\src\Tools\WaveEngine.HLSLEverywhere\HLSLTranslator.cs:Zeile 246.
   bei WaveEngine.Assets.Exporters.EffectExporter.TranslateShaderToBackend(GraphicsBackend graphicsBackend, PreprocessShader cleanedSource, ShaderStages stage, String entryPoint, CompilerParameters parameters) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 296.
   bei WaveEngine.Assets.Exporters.EffectExporter.Precompile(GraphicsBackend graphicsBackend, PreprocessShader cleanedSource, PassSection pass, String[] directives, PrecompiledCombination compiledCombination, List`1 files) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 211.
   bei WaveEngine.Assets.Exporters.EffectExporter.PrecompileCombination(GraphicsBackend graphicsBackend, List`1 files, ShaderAnalyzer analyzer, PassSection pass, PrecompiledPass precompiledPass, String[] directives) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 205.
   bei WaveEngine.Assets.Exporters.EffectExporter.ExportCompiledShaders(Guid id, String shaderSource, ProjectProfile projectProfile, EffectProfile profile, GraphicsBackend graphicsBackend, DirectivesGroup[]& directivesGroups, List`1& precompiledPasses, GraphicsResourceInfo[]& precompiledResourceLayoutInfo, List`1 files, String projectContent) in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 184.
   bei WaveEngine.Assets.Exporters.EffectExporter.<GenerateAssetParts>d__4.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\Effect\EffectExporter.cs:Zeile 56.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WaveEngine.Assets.Exporters.AssetExporter`2.<ExportOutputFile>d__1.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\AssetExporter`2.cs:Zeile 36.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei WaveEngine.Assets.Exporters.BaseAssetExporter`2.<BaseExport>d__3.MoveNext() in C:\agent\_work\3\s\src\Engine\Common\WaveEngine.Assets\Exporters\BaseAssetExporter`2.cs:Zeile 65.	Fisch.Android	C:\Users\fbusc\Documents\Fisch\Content\Computes\Gaussian.wefx

**Comment by jcant0n** [comment]
Hi,

This is an issue, the Android and iOS platforms templates are not published right now, so its should appear disabled.
We will try to upload a new preview today or tomorrow to fix this.

We are testing the templates for Android and iOS internally and hope to publish this soon.

Thanks for your feedback and sorry for the inconveniences.
