### ISSUE TITLE
Cannot run any example!

### ISSUE THREAD

**Issue by Cimbro** [EvergineTeam/Feedback#56]
Hi Guys,
we are very interested in a solution like yours , in particular for havign 3d graphics on web.
We are trying to run your example under web (we are interested in webassembly) but without success...

We have this straage message

1>Asset exported: 'C:\Users\danie\Desktop\AreaLightsDemo-main\Content\Models\DamagedHelmet\DamagedHelmet.bin.wefile'
1>Asset exported: 'C:\Users\danie\Desktop\AreaLightsDemo-main\Content\Models\FlightHelmet\FlightHelmet.bin.wefile'
1>EXEC : warning : file packager is creating an asset bundle of 352 MB. this is very large, and browsers might have trouble loading it. See https://hacks.mozilla.org/2015/02/synchronous-execution-and-filesystem-access-in-emscripten/
1>C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error : The Windows Subsystem for Linux dotnet environment may not be properly setup, and you may need to run the environment setup script. Open an Ubuntu WSL shell and run:
1>C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error :
1>C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error : wslpath "C:\Users\danie\.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\scripts\dotnet-setup.sh"
1>C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error :
1>C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error :
1>C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018: errore imprevisto dell'attività "PackageProjectTask".
1>C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018: System.InvalidOperationException: Failed to setup WSL environment.
1>C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018: in WaveEngine.Targets.Web.Tasks.PackageProjectTask.ValidateEmscripten() in C:\agent_work\3\s\src\Targets\Web\WaveEngine.Targets.Web.Tasks\PackageProjectTask.cs:riga 174
1>C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018: in WaveEngine.Targets.Web.Tasks.PackageProjectTask.Execute() in C:\agent_work\3\s\src\Targets\Web\WaveEngine.Targets.Web.Tasks\PackageProjectTask.cs:riga 66
1>C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018: in Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\WaveEngine.Targets.Web.targets(51,5): error MSB4018: in Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext()
1>Compilazione progetto "AreaLightsDemo.Web.csproj" NON COMPLETATA.

We have last version of visual studio with net5.
Any suggestions?
Regards
D

**Comment by davilovick** [comment]
Hi Cimbro, 
Sorry for the delay, in that case, the compilation output is telling that you need to properly setup the WSL environment to compile wave projects for web.

In that case, you need to open a Terminal in WSL and execute the specified command:
\`wslpath "C:\Users\danie.nuget\packages\waveengine.targets.web\3.1.0.6768-preview2\build\scripts\dotnet-setup.sh"\`

Note: Is important to copy the ` characters
After that, maybe you need to reboot your machine :)
