### ISSUE TITLE
Coding questions...

### ISSUE THREAD

**Issue by FrankBusch68** [EvergineTeam/Feedback#57]
Hi,
some more questions...
1. How can I get information about input (keyboard, mouse, touching, gestures like swiping of zooming)
2. Can I get information which element a user clicked/tapped on? If so, how?
3. What Do I have to do to render some text into the Scene (best 3D from defined font, otherwise just add it flat)
4. Can I define an animation (for any entity, including cam) and then just start it? For example rolling a sphere along a bow or driving the camera softly along a softly splined line.
5. How can I define materials for polished chrome or glass?
6. is it possible to combine WaveEngine with simple Xamarin? Usual Forms and stuff from Xamarin and then start a Scene and interact with it, get back to Xamarin...

So much things waiting to be learned ;)
Thanks in advance
Frank

**Comment by Hromon** [comment]
_ -> i don't know.

1: ![image](https://user-images.githubusercontent.com/29508584/107635478-46881500-6c7c-11eb-8c85-cb68a7f917b7.png)
2: _
3: Include NoesisGUI and use example https://github.com/WaveEngine/MixedRealityToolkit-WaveEngine/tree/master/Samples/WaveEngine_MRTK_Demo
4: _
5: Use shader
6: _

**Comment by FrankBusch68** [comment]
Thanks so far. 
I found the dispatchers for mouse, keyboard and touch. 
Next is to take a look at NoesisGUI. 
What do I have to do with the shaders? Lots of undocumented calls... Please guide me one step further to give me a point to really start.

**Comment by davilovick** [comment]
Hi FrankBush,
Respect materials and create the chrome materials , if you create a StandardEffect material, you could set Metal and Roughness as typical PBR materials. 
To create glass materials, you could set the Alpha layer to the material.

Best regards
