### ISSUE TITLE
Noesis.GUI.ParseXaml fails with fatal AccessViolationException

### ISSUE THREAD

**Issue by coman3** [EvergineTeam/Feedback#64]
Library version: 3.1.0.6768-preview2
Using the following code
```cs
var assetsService = Application.Current.Container.Resolve<AssetsDirectoryBase>();
var pageSource = assetsService.ReadAsStringAsync("UI/Page1.xaml").Result;
var gui = (Noesis.FrameworkElement)Noesis.GUI.ParseXaml(pageSource);
```
fails to parse the XAML file due to the error:
```
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
```
Using code generated Framework elements works fine, just the parsing that fails.
Is there another way to parse a XAML file (within contents), or has this not been implemented yet?

I can confirm that the `Noesis.GUI.ParseXaml` works on the Noesis.GUI nuget - but because you have merged this into your own assembly, I can not use that library.

**Comment by coman3** [comment]
I guess a question here as well is why WaveEngine.NoesisGUI has to **embed** the Noesis.GUI sources, instead of adding Noesis.GUI as a dependency?

**Comment by minolo** [comment]
Hi there @coman3 

The issue you are facing might be caused by the fact that the NoesisService is not registered yet when that code is executed. Please add this line to your main application constructor method, where you can find all service registrations:

``` C#
this.Container.RegisterType<NoesisService>();
```

See if that works for you.

Also, to address your question about embedding sources: we developed the integration some time ago when there were no nuget packages for NoesisGUI. In addition, we had to make some modifications to the provided proxy code for it to work with our engine.

We are currently working on integrating nuget packages though.

I hope to have helped!

**Comment by coman3** [comment]
Hi @minolo,

Thanks for getting back to me about this. I seem to still be having this issue even after registering the noesis service within the application container.

Just to confirm I am calling the GUI.ParseXaml within a (code only) scene 'override CreateScene()' after the base.CreateScene() has executed. Does this need to be done after some kind of event?

Also, do you happen to know of any samples / where to get started for rendering Noesis directly to the camera / screen using the WaveEngine.NoesisGUI package?

**Comment by zaidorx** [comment]
I am also interested in a solution to this. I am having exactly the same issue.

**Comment by minolo** [comment]
Hi there!

I'm sorry to say that this is not a use case we have tested internally, so I'd need a little more time to take a look at it.

In the meantime I can offer some advice. Just to know, where are you executing that code? In a CreateScene method? The service might not have initialized when you try to parse the XAML. Give me more details about that and I will try to reproduce it.

As an aside, could I ask why are you doing it this specific way? If you just need to create a Noesis panel which loads a XAML you created, you can follow the tutorials pointed at in #22. If this is not valid for you, please get back to me and I'll try to help further!

Best regards.
