### ISSUE TITLE
WaveEngine.Bullet RigidBody3d.ApplyTorque applied a force instead of a torque.

### ISSUE THREAD

**Issue by tylerm42** [EvergineTeam/Feedback#69]
I'm using WaveEngine.Bullet to move objects around via forces and torques.

I was using the `RigidBody3d.ApplyTorque` function to rotate objects. I applied a torque <0, 100, 0> on an object to rotate it along the Y axis, or spin the object around so it will face towards the camera. Instead it will float upwards. `RigidBody3d.ApplyTorqueImpulse(new Vector3(0, 100, 0))` does work correctly, it seems that `RigidBody3d.ApplyTorque(new Vector3(0, 100, 0))` might be a linear force instead of an angular torque.

Here's a picture explaining this better.
![torquebugexample](https://user-images.githubusercontent.com/81641228/113025828-61dcb000-9156-11eb-9997-c0275aad5ec2.png)

**Comment by emepetres** [comment]
Thank you @tylerm42 for your report and sorry for the late response. We'll check whenever possible. If you need a quick resolution, please contact our [priority support](https://evergine.com/priority-support/).

**Comment by davilovick** [comment]
Hi @tylerm42 
Sorry for the late, late response. We have fixed this issue and will come in the next release.
As a workaround, I suggest you to change the following code:
Instead of use `rigidBodyComponent.ApplyImpulse(...)`
try this:`(rigidBodyComponent.InternalBody as IRigidBody3D).ApplyImpulse(...)`

**Comment by davilovick** [comment]
Hi @tylerm42,

We've just released Evergine 2022.2.16.5, and among other fixes, this version comes with this issue fixed.

Best regards
