### ISSUE TITLE
Wave engine 2.5.0 Deserializer 

### ISSUE THREAD

**Issue by XorbiterGit** [EvergineTeam/Feedback#75]
First time using Wave engine tried. Tried to login to my account, then this following error

deserializer message error 
![Screenshot 2021-04-26 165242](https://user-images.githubusercontent.com/38113433/116103462-e6681300-a6af-11eb-90b2-d44a0913ae7a.png)

**Comment by jcant0n** [comment]
Hello,

The new version doesn't require email account, try the latest WaveEngine version: https://waveengine.net/Downloads


Hope this helps!
