### ISSUE TITLE
A Xamarin:Forms (.Net MAUI) UI Element/Renderer

### ISSUE THREAD

**Issue by Agredo** [EvergineTeam/Feedback#83]
It would be awaesome if there would be a Xamarin.Forms (in feature .Net MAUI) Renderer. 
It would be great when we could add the engine like a SwapChainPanel in XAML (for UWP and WPF) then it would be finally possible to build easy Xamarin.Forms (https://github.com/xamarin/Xamarin.Forms) applications with 3D interactions and we could edit models in the wave engine editor!

**Comment by rubit0** [comment]
@MarcosCobena Do you maybe have a sample project where it works inside "classic" Xamarin.Forms as a view?

**Comment by Agredo** [comment]
There it is! Thank you! https://evergine.com/evergine-release-september-2023/#Dotnet_MAUI_support
