### ISSUE TITLE
Wave Engine 3.3 crash on startup (SharpGen runtime)

### ISSUE THREAD

**Issue by jfaz1** [EvergineTeam/Feedback#97]
Hello, 

Recently installed Wave Engine to give it a try, but I get these errors (following with a crash) when opening an empty project:
![image](https://user-images.githubusercontent.com/25165780/137573658-535f5f23-f5b4-408e-b074-937e47bbbcfa.png)

I also tried on 3.2 and it crashes as well.

I have all the .Net components from the Visual Studio installer installed. What can I try?

**Comment by minolo** [comment]
Hi there!

What WaveEngine build version are you using?

**Comment by jfaz1** [comment]
Fixed it by installing Windows 11. Seems like it was a Windows 10 LTSC issue.

**Comment by minolo** [comment]
Great, I'm glad to hear the error is gone now.
